#!/bin/bash

# Original by: Danct12 <danct12@disroot.org>
# SPDX-License-Identifier: GPL-3.0-or-later

build() {
    local mod

    add_module "dm-crypt"
    if [[ $CRYPTO_MODULES ]]; then
        for mod in $CRYPTO_MODULES; do
            add_module "$mod"
        done
    else
        add_all_modules "/crypto/"
    fi

    add_binary "cryptsetup"
    add_binary "dmsetup"
    add_file "/usr/lib/udev/rules.d/10-dm.rules"
    add_file "/usr/lib/udev/rules.d/13-dm-disk.rules"
    add_file "/usr/lib/udev/rules.d/95-dm-notify.rules"
    add_file "/usr/lib/initcpio/udev/11-dm-initramfs.rules" "/usr/lib/udev/rules.d/11-dm-initramfs.rules"
    add_file "/usr/lib/initcpio/hooks/kupfer-functions.sh"

    add_binary /usr/bin/osk-sdl
    add_file /etc/osk.conf

    ### add DRI drivers so we can have hw accel with a swrast fallback

    add_binary /usr/lib/dri/msm_dri.so
    add_binary /usr/lib/dri/swrast_dri.so

    add_binary /usr/lib/libGL.so.1
    add_binary /usr/lib/libEGL.so.1
    add_binary /usr/lib/libEGL_mesa.so.0

    [ -f /usr/share/glvnd/egl_vendor.d/50_mesa.json ] && add_file /usr/share/glvnd/egl_vendor.d/50_mesa.json

    ttf_font=$(grep "^keyboard-font\s" /etc/osk.conf|cut -f3 -d' ')
    [ -f "$ttf_font" ] && add_file "$ttf_font"

    add_runscript
}

help() {
    cat <<HELPEOF
This hook loads osk-sdl to decrypt the filesystem.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
