#!/usr/bin/ash

# Author: Syboxez
# Init Shim: Will mount and load a secondary initramfs

source /usr/lib/initcpio/hooks/kupfer-functions.sh

run_hook() {
	set -e # Abort on error
	unset LOOPDEV

	if [ -n "$kupfer_boot_uuid" ]; then
		query="UUID=${kupfer_boot_uuid}"
	else
		query="LABEL=kupfer_boot"
	fi

	for part in /dev/sd?[0-9]* ; do
		! scan_partitions "$part" "$query" || break
	done

	echo "Result in run_hook is: $RESULT"

	if [ -z "$RESULT" ]; then
		panic "No boot partition ${query} found. Erroring out..."
	fi

	busybox mkdir -p /mnt

	busybox mount "$RESULT" /mnt

	export REALINITRAMFS="/mnt/initramfs-linux.img"
	[ -f "$REALINITRAMFS" ] || panic "UNABLE TO FIND INITRAMFS $REALINITRAMFS"

	# Extract new initramfs (code from the Mobian project)
	#if command -v zstd > /dev/null && zstd --test "$REALINITRAMFS"; then
	#	zstd -d -c -f "$REALINITRAMFS" | busybox cpio -u -i
	if busybox gzip -t "$REALINITRAMFS"; then
		busybox gzip -d -c -f "$REALINITRAMFS" | busybox cpio -u -i
	elif busybox xz -t "$REALINITRAMFS"; then
		busybox xz -d -c -f "$REALINITRAMFS" | busybox cpio -u -i
	elif busybox unlzma -t "$REALINITRAMFS"; then
		busybox unlzma -c -f "$REALINITRAMFS" | busybox cpio -u -i
	else
		panic "unable to decompress initramfs"
	fi

	# Clean up
	busybox umount /mnt
	if [ -n "$LOOPDEV" ]; then
		busybox losetup -d "$LOOPDEV"
	fi

	busybox umount /dev/pts || true
	busybox umount /dev || true
	busybox umount /sys || true
	[ -d /dev/pts ] && busybox rmdir /dev/pts


	# exec new init binary to keep same PID
	exec /init
}

